// <auto-generated />
using System;
using DeskFlow.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DeskFlow.Infrastructure.Migrations
{
    [DbContext(typeof(DeskFlowDbContext))]
    [Migration("20260324224153_InitialPostgres")]
    partial class InitialPostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DeskFlow.Core.Entities.AdjuntoTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ComentarioId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("Tamaño")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid");

                    b.Property<string>("TipoArchivo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ComentarioId");

                    b.HasIndex("TicketId");

                    b.ToTable("AdjuntosTicket");
                });

            modelBuilder.Entity("DeskFlow.Core.Entities.Area", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("DeskFlow.Core.Entities.ArticuloRelacionado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArticuloOrigenId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArticuloRelacionadoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ArticuloRelacionadoId");

                    b.HasIndex("ArticuloOrigenId", "ArticuloRelacionadoId")
                        .IsUnique();

                    b.ToTable("ArticulosRelacionados");
                });

            modelBuilder.Entity("DeskFlow.Core.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DatosAnteriores")
                        .HasColumnType("jsonb");

                    b.Property<string>("DatosNuevos")
                        .HasColumnType("jsonb");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("EntidadId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IP")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FechaCreacion");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("TenantId", "Entidad", "EntidadId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("DeskFlow.Core.Entities.BaseConocimiento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<Guid>("AutorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EsPublico")
                        .HasColumnType("boolean");

                    b.Property<string>("Etiquetas")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SubcategoriaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Vistas")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("SubcategoriaId");

                    b.HasIndex("TenantId", "Activo");

                    b.HasIndex("TenantId", "CategoriaId");

                    b.ToTable("BaseConocimiento");
                });

            modelBuilder.Entity("DeskFlow.Core.Entities.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Icono")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("DeskFlow.Core.Entities.ComentarioTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EsInterno")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ComentariosTicket");
                });

            modelBuilder.Entity("DeskFlow.Core.Entities.EncuestaConfiguracion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("EscalaMaxima")
                        .HasColumnType("integer");

                    b.Property<int>("EscalaMinima")
                        .HasColumnType("integer");

                    b.Property<string>("Pregunta")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("EncuestaConfiguraciones");
                });

            modelBuilder.Entity("DeskFlow.Core.Entities.EncuestaRespuesta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comentario")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaRespuesta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Puntuacion")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TecnicoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TecnicoId");

                    b.HasIndex("TicketId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("TenantId", "TicketId")
                        .IsUnique();

                    b.ToTable("EncuestaRespuestas");
                });

            modelBuilder.Entity("DeskFlow.Core.Entities.EstadoTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("EsFinal")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("EstadosTicket");
                });

            modelBuilder.Entity("DeskFlow.Core.Entities.Etiqueta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Nombre")
                        .IsUnique();

                    b.ToTable("Etiquetas");
                });

            modelBuilder.Entity("DeskFlow.Core.Entities.HistorialTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("EstadoAnteriorId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EstadoNuevoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EstadoAnteriorId");

                    b.HasIndex("EstadoNuevoId");

                    b.HasIndex("TicketId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("HistorialTickets");
                });

            modelBuilder.Entity("DeskFlow.Core.Entities.Notificacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Leida")
                        .HasColumnType("boolean");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TicketId")
                        .HasColumnType("uuid");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FechaCreacion");

                    b.HasIndex("TicketId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("TenantId", "UsuarioId", "Leida");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("DeskFlow.Core.Entities.Plantilla", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("CategoriaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CreadoPorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("CreadoPorId");

                    b.HasIndex("TenantId");

                    b.ToTable("Plantillas");
                });

            modelBuilder.Entity("DeskFlow.Core.Entities.Prioridad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("TiempoResolucionSLA_Horas")
                        .HasColumnType("integer");

                    b.Property<int>("TiempoRespuestaSLA_Horas")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Prioridades");
                });

            modelBuilder.Entity("DeskFlow.Core.Entities.Rol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Nombre")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("DeskFlow.Core.Entities.SLAConfiguracion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CategoriaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PrioridadId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("TiempoResolucion_Horas")
                        .HasColumnType("integer");

                    b.Property<int>("TiempoRespuesta_Horas")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("PrioridadId");

                    b.HasIndex("TenantId");

                    b.ToTable("SLAConfiguraciones");
                });

            modelBuilder.Entity("DeskFlow.Core.Entities.Subcategoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("TenantId");

                    b.ToTable("Subcategorias");
                });

            modelBuilder.Entity("DeskFlow.Core.Entities.Sucursal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Direccion")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Sucursales");
                });

            modelBuilder.Entity("DeskFlow.Core.Entities.TecnicoCategoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TecnicoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("TecnicoId");

                    b.HasIndex("TenantId", "TecnicoId", "CategoriaId")
                        .IsUnique();

                    b.ToTable("TecnicoCategorias");
                });

            modelBuilder.Entity("DeskFlow.Core.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("ColorPrimario")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Dominio")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Logo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Dominio")
                        .IsUnique();

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("DeskFlow.Core.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AreaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Asunto")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("EstadoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("FechaAsignacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaInicioUltimaPausa")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaLimiteSLA")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaResolucion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("PrioridadId")
                        .HasColumnType("uuid");

                    b.Property<int>("SLAEstado")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SubcategoriaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SucursalId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SupervisorId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TecnicoAsignadoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("TiempoPausadoMinutos")
                        .HasColumnType("integer");

                    b.Property<Guid>("UsuarioCreadorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("EstadoId");

                    b.HasIndex("FechaCreacion");

                    b.HasIndex("PrioridadId");

                    b.HasIndex("SubcategoriaId");

                    b.HasIndex("SucursalId");

                    b.HasIndex("SupervisorId");

                    b.HasIndex("TecnicoAsignadoId");

                    b.HasIndex("UsuarioCreadorId");

                    b.HasIndex("TenantId", "EstadoId");

                    b.HasIndex("TenantId", "Numero")
                        .IsUnique();

                    b.HasIndex("TenantId", "TecnicoAsignadoId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("DeskFlow.Core.Entities.TicketEtiqueta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EtiquetaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EtiquetaId");

                    b.HasIndex("TicketId", "EtiquetaId")
                        .IsUnique();

                    b.ToTable("TicketEtiquetas");
                });

            modelBuilder.Entity("DeskFlow.Core.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("AreaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RolId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SucursalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("RolId");

                    b.HasIndex("SucursalId");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("DeskFlow.Core.Entities.AdjuntoTicket", b =>
                {
                    b.HasOne("DeskFlow.Core.Entities.ComentarioTicket", "Comentario")
                        .WithMany("Adjuntos")
                        .HasForeignKey("ComentarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DeskFlow.Core.Entities.Ticket", "Ticket")
                        .WithMany("Adjuntos")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comentario");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("DeskFlow.Core.Entities.Area", b =>
                {
                    b.HasOne("DeskFlow.Core.Entities.Tenant", "Tenant")
                        .WithMany("Areas")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("DeskFlow.Core.Entities.ArticuloRelacionado", b =>
                {
                    b.HasOne("DeskFlow.Core.Entities.BaseConocimiento", "ArticuloOrigen")
                        .WithMany("ArticulosRelacionados")
                        .HasForeignKey("ArticuloOrigenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeskFlow.Core.Entities.BaseConocimiento", "Articulo")
                        .WithMany()
                        .HasForeignKey("ArticuloRelacionadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Articulo");

                    b.Navigation("ArticuloOrigen");
                });

            modelBuilder.Entity("DeskFlow.Core.Entities.AuditLog", b =>
                {
                    b.HasOne("DeskFlow.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DeskFlow.Core.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DeskFlow.Core.Entities.BaseConocimiento", b =>
                {
                    b.HasOne("DeskFlow.Core.Entities.Usuario", "Autor")
                        .WithMany()
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DeskFlow.Core.Entities.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DeskFlow.Core.Entities.Subcategoria", "Subcategoria")
                        .WithMany()
                        .HasForeignKey("SubcategoriaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DeskFlow.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("Categoria");

                    b.Navigation("Subcategoria");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("DeskFlow.Core.Entities.Categoria", b =>
                {
                    b.HasOne("DeskFlow.Core.Entities.Tenant", "Tenant")
                        .WithMany("Categorias")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("DeskFlow.Core.Entities.ComentarioTicket", b =>
                {
                    b.HasOne("DeskFlow.Core.Entities.Ticket", "Ticket")
                        .WithMany("Comentarios")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeskFlow.Core.Entities.Usuario", "Usuario")
                        .WithMany("Comentarios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ticket");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DeskFlow.Core.Entities.EncuestaConfiguracion", b =>
                {
                    b.HasOne("DeskFlow.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("DeskFlow.Core.Entities.EncuestaRespuesta", b =>
                {
                    b.HasOne("DeskFlow.Core.Entities.Usuario", "Tecnico")
                        .WithMany()
                        .HasForeignKey("TecnicoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DeskFlow.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DeskFlow.Core.Entities.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DeskFlow.Core.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tecnico");

                    b.Navigation("Tenant");

                    b.Navigation("Ticket");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DeskFlow.Core.Entities.Etiqueta", b =>
                {
                    b.HasOne("DeskFlow.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("DeskFlow.Core.Entities.HistorialTicket", b =>
                {
                    b.HasOne("DeskFlow.Core.Entities.EstadoTicket", "EstadoAnterior")
                        .WithMany("HistorialesAnteriores")
                        .HasForeignKey("EstadoAnteriorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DeskFlow.Core.Entities.EstadoTicket", "EstadoNuevo")
                        .WithMany("HistorialesNuevos")
                        .HasForeignKey("EstadoNuevoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DeskFlow.Core.Entities.Ticket", "Ticket")
                        .WithMany("Historial")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeskFlow.Core.Entities.Usuario", "Usuario")
                        .WithMany("Historial")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EstadoAnterior");

                    b.Navigation("EstadoNuevo");

                    b.Navigation("Ticket");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DeskFlow.Core.Entities.Notificacion", b =>
                {
                    b.HasOne("DeskFlow.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DeskFlow.Core.Entities.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DeskFlow.Core.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("Ticket");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DeskFlow.Core.Entities.Plantilla", b =>
                {
                    b.HasOne("DeskFlow.Core.Entities.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DeskFlow.Core.Entities.Usuario", "CreadoPor")
                        .WithMany()
                        .HasForeignKey("CreadoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DeskFlow.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("CreadoPor");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("DeskFlow.Core.Entities.Prioridad", b =>
                {
                    b.HasOne("DeskFlow.Core.Entities.Tenant", "Tenant")
                        .WithMany("Prioridades")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("DeskFlow.Core.Entities.Rol", b =>
                {
                    b.HasOne("DeskFlow.Core.Entities.Tenant", "Tenant")
                        .WithMany("Roles")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("DeskFlow.Core.Entities.SLAConfiguracion", b =>
                {
                    b.HasOne("DeskFlow.Core.Entities.Categoria", "Categoria")
                        .WithMany("SLAConfiguraciones")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DeskFlow.Core.Entities.Prioridad", "Prioridad")
                        .WithMany("SLAConfiguraciones")
                        .HasForeignKey("PrioridadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DeskFlow.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Prioridad");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("DeskFlow.Core.Entities.Subcategoria", b =>
                {
                    b.HasOne("DeskFlow.Core.Entities.Categoria", "Categoria")
                        .WithMany("Subcategorias")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeskFlow.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("DeskFlow.Core.Entities.Sucursal", b =>
                {
                    b.HasOne("DeskFlow.Core.Entities.Tenant", "Tenant")
                        .WithMany("Sucursales")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("DeskFlow.Core.Entities.TecnicoCategoria", b =>
                {
                    b.HasOne("DeskFlow.Core.Entities.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DeskFlow.Core.Entities.Usuario", "Tecnico")
                        .WithMany()
                        .HasForeignKey("TecnicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DeskFlow.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Tecnico");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("DeskFlow.Core.Entities.Ticket", b =>
                {
                    b.HasOne("DeskFlow.Core.Entities.Area", "Area")
                        .WithMany("Tickets")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DeskFlow.Core.Entities.Categoria", "Categoria")
                        .WithMany("Tickets")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DeskFlow.Core.Entities.EstadoTicket", "Estado")
                        .WithMany("Tickets")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DeskFlow.Core.Entities.Prioridad", "Prioridad")
                        .WithMany("Tickets")
                        .HasForeignKey("PrioridadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DeskFlow.Core.Entities.Subcategoria", "Subcategoria")
                        .WithMany("Tickets")
                        .HasForeignKey("SubcategoriaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DeskFlow.Core.Entities.Sucursal", "Sucursal")
                        .WithMany("Tickets")
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DeskFlow.Core.Entities.Usuario", "Supervisor")
                        .WithMany("TicketsSupervisados")
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DeskFlow.Core.Entities.Usuario", "TecnicoAsignado")
                        .WithMany("TicketsAsignados")
                        .HasForeignKey("TecnicoAsignadoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DeskFlow.Core.Entities.Tenant", "Tenant")
                        .WithMany("Tickets")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DeskFlow.Core.Entities.Usuario", "UsuarioCreador")
                        .WithMany("TicketsCreados")
                        .HasForeignKey("UsuarioCreadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Categoria");

                    b.Navigation("Estado");

                    b.Navigation("Prioridad");

                    b.Navigation("Subcategoria");

                    b.Navigation("Sucursal");

                    b.Navigation("Supervisor");

                    b.Navigation("TecnicoAsignado");

                    b.Navigation("Tenant");

                    b.Navigation("UsuarioCreador");
                });

            modelBuilder.Entity("DeskFlow.Core.Entities.TicketEtiqueta", b =>
                {
                    b.HasOne("DeskFlow.Core.Entities.Etiqueta", "Etiqueta")
                        .WithMany("TicketEtiquetas")
                        .HasForeignKey("EtiquetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeskFlow.Core.Entities.Ticket", "Ticket")
                        .WithMany("Etiquetas")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Etiqueta");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("DeskFlow.Core.Entities.Usuario", b =>
                {
                    b.HasOne("DeskFlow.Core.Entities.Area", "Area")
                        .WithMany("Usuarios")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DeskFlow.Core.Entities.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DeskFlow.Core.Entities.Sucursal", "Sucursal")
                        .WithMany("Usuarios")
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DeskFlow.Core.Entities.Tenant", "Tenant")
                        .WithMany("Usuarios")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Rol");

                    b.Navigation("Sucursal");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("DeskFlow.Core.Entities.Area", b =>
                {
                    b.Navigation("Tickets");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("DeskFlow.Core.Entities.BaseConocimiento", b =>
                {
                    b.Navigation("ArticulosRelacionados");
                });

            modelBuilder.Entity("DeskFlow.Core.Entities.Categoria", b =>
                {
                    b.Navigation("SLAConfiguraciones");

                    b.Navigation("Subcategorias");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("DeskFlow.Core.Entities.ComentarioTicket", b =>
                {
                    b.Navigation("Adjuntos");
                });

            modelBuilder.Entity("DeskFlow.Core.Entities.EstadoTicket", b =>
                {
                    b.Navigation("HistorialesAnteriores");

                    b.Navigation("HistorialesNuevos");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("DeskFlow.Core.Entities.Etiqueta", b =>
                {
                    b.Navigation("TicketEtiquetas");
                });

            modelBuilder.Entity("DeskFlow.Core.Entities.Prioridad", b =>
                {
                    b.Navigation("SLAConfiguraciones");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("DeskFlow.Core.Entities.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("DeskFlow.Core.Entities.Subcategoria", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("DeskFlow.Core.Entities.Sucursal", b =>
                {
                    b.Navigation("Tickets");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("DeskFlow.Core.Entities.Tenant", b =>
                {
                    b.Navigation("Areas");

                    b.Navigation("Categorias");

                    b.Navigation("Prioridades");

                    b.Navigation("Roles");

                    b.Navigation("Sucursales");

                    b.Navigation("Tickets");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("DeskFlow.Core.Entities.Ticket", b =>
                {
                    b.Navigation("Adjuntos");

                    b.Navigation("Comentarios");

                    b.Navigation("Etiquetas");

                    b.Navigation("Historial");
                });

            modelBuilder.Entity("DeskFlow.Core.Entities.Usuario", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("Historial");

                    b.Navigation("TicketsAsignados");

                    b.Navigation("TicketsCreados");

                    b.Navigation("TicketsSupervisados");
                });
#pragma warning restore 612, 618
        }
    }
}
